name: Build Downloader for PC (Ubuntu)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Downloader:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Downloader
        run: |
              echo "Coming soon..."

