name: Build Downloader for Switch

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Downloader:
    runs-on: ubuntu-latest
    #container: devkitpro/devkita64_devkitarm
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install devkitpro
        run: |
              wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
              sudo dpkg -i devkitpro-pacman.deb
              sudo dkp-pacman -S --noconfirm switch-dev switch-glfw switch-mesa switch-glm switch-curl switch-zlib

      #- name: Install necessary libraries
      #  run: |
      #        sudo dkp-pacman -R --noconfirm $(dkp-pacman -Ssq "switch-*")

      - name: Build Downloader
        run: |
              echo ##########################
              echo #     SETTING PATH       #
              echo ##########################
              echo
              export DEVKITPRO=/opt/devkitpro
              export DEVKITARM=${DEVKITPRO}/devkitARM
              export DEVKITPPC=${DEVKITPRO}/devkitPPC
              export PATH=${DEVKITPRO}/tools/bin:$PATH
              make -j$(nproc)
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Downloader.nro
          path: Downloader/out/Downloader.nro
