name: Build Downloader for Switch

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Downloader:
    runs-on: ubuntu-latest
    #container: devkitpro/devkita64_devkitarm
    container: hamletdufromage/devkita64_devkitarm

    steps:
      - uses: actions/checkout@v2
      
      - name: Install necessary libraries
        run: |
              sudo dkp-pacman -R --noconfirm $(dkp-pacman -Ssq "switch-*" | grep -v hactool)
              sudo dkp-pacman -S --noconfirm switch-dev switch-glfw switch-mesa switch-glm switch-curl switch-zlib

      - name: Build Downloader
        run: |
              make -j$(nproc)
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Downloader.nro
          path: Downloader/out/Downloader.nro
